### ISSUE TITLE
Create a ruler

### ISSUE THREAD

**Issue by FCBTruong** [FCBTruong/BTL_CNPM#1]
+ 1 thước có chia vạch các số trong khoảng từ 300 - 600.
+ Có các ô có thể nhập số vào.

**Comment by 18021452** [comment]
![93334383_2618073318433657_8734141993023700992_n (1)](https://user-images.githubusercontent.com/57910568/79100203-28b5ff00-7d90-11ea-9deb-17afce604e3a.jpg)
Mẫu thước kẻ chia ô  và mũi tên chuyển ô !

**Comment by FCBTruong** [comment]
Done
