### ISSUE TITLE
Bugs (Kiểm thử lần 1)

### ISSUE THREAD

**Issue by Trinh67** [FCBTruong/BTL_CNPM#12]
+, Lỗi font chữ tiếng Việt.
+, Chưa có âm thanh trong game.
+, Giao diện 2 game lúc đầu giống nhau.
+, Sau khi chơi thắng cần thêm biểu tượng tick ngoài màn chơi để thể hiện đã thắng.
+, Khung bóng còn thô, cần sửa lại.
+, Khi chuyển ngôn ngữ  từ tiếng Việt sang tiếng Anh bị lỗi.
+, Khi di chuột vào biểu tượng game thì chữ cũng nên đổi màu.

**Comment by Trinh67** [comment]
+, Chưa có âm thanh trong game.

**Comment by FCBTruong** [comment]
Done
