### ISSUE TITLE
Assets for game

### ISSUE THREAD

**Issue by FCBTruong** [FCBTruong/BTL_CNPM#5]
- Hình ảnh, âm thanh cho game:
+ Background
+ Thước chia vạch
+ Màn hình thắng, thua
 ...
Tất cả hình ảnh trên game mẫu.

**Comment by Trinh67** [comment]
Còn thiếu âm thanh trong game

**Comment by Trinh67** [comment]
Còn thiếu âm thanh trong game

**Comment by 18021452** [comment]
nhạc nền vs nhạc lúc kết thúc có rồi nhá

**Comment by Trinh67** [comment]
Thế phần này oke rồi nhé !
